name: dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - black
  - cookiecutter
  - flake8
  - git
  - git-lfs
  - isort
  - mamba
  - nodejs
  - pre-commit
  - snakefmt
  - snakemake
# support for R linting utilities
  - r-devtools
  - r-docopt
  - r-lintr
  - r-styler
  - r-usethis
